# Generated by Django 3.1.5 on 2021-01-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('steps', models.CharField(max_length=7000, null=True)),
                ('ingredients', models.CharField(max_length=5000, null=True)),
                ('food_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
